app:
  name: "{% AppName %}"

  config:

    mailer:
      provider: "mailgun"
      sender: "support@{% AppName %}.com"

    oauth:
      google: false
      facebook: false
      linkedin: false
      github: false

    multilang:
      picker: true
      languages:
        - short: en
          code: en-US
        - short: es
          code: es-ES


