app:
  name: "{% AppName %}"

  author: "{% AppName %} <support@{% AppName %}.com>"
  license: "BSD 3-Clause"

  homepage: "https://github.com/hofstadter-io/hof-starter-app"

  keywords:
    - "Hofstadter"
    - "Studios"
    - "HofStarterApp"
    - "hof-starter-app"
    - "minimal"

